server.port=${SERVER_PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1}
spring.h2.console.enabled=true
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
